{% set name = "torch_scatter" %}
{% set version = "2.0.6" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c664656a6c006d5221b2d51ce51eca0bbf39e85a180fdd6d3ad42cb28b5a536

build:
  number: 2
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [linux64 and cuda_compiler_version not in (undefined, 'None')]
    - export CC="$GCC"   # [linux64 and cuda_compiler_version not in (undefined, 'None')]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pytorch-cpu                            # [build_platform != target_platform and osx or cuda_compiler_version in (undefined, 'None')]
    - pytorch-gpu                            # [build_platform != target_platform and cuda_compiler_version not in (undefined, 'None')]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]
  host:
    - python
    - pip
    - pytorch-cpu  # [osx or cuda_compiler_version in (undefined, 'None')]
    - pytorch-gpu  # [cuda_compiler_version not in (undefined, 'None')]
    - setuptools
    - pytest-runner
  run:
    - python
    - pytorch
    - {{ pin_compatible('pytorch-gpu') }}  # [cuda_compiler_version not in (undefined, 'None')]
    - {{ pin_compatible('pytorch-cpu') }}  # [osx or cuda_compiler_version in (undefined, 'None')]
    - pytest
    - pytest-cov
test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
