{% set name = "torch_scatter" %}
{% set version = "2.0.5" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 148fbe634fb9e9465dbde2ab337138f63650ed8abbac42bb3f565e3fe92e9b2f

build:
  number: 0
  skip: true  # [win or cuda_compiler_version == 'None' or cuda_compiler_version == '10.2']
  script:
    - export FORCE_CUDA="1"    # [linux]
    - export CC="$GCC"   # [linux]
#    - export NVCC_FLAGS="--compiler-bindir=${CC}"    # [linux64 and cuda_compiler_version != 'None']
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux]
  host:
    - python
    - pip
    - pytorch
    - setuptools
    - pytest-runner
  run:
    - python
    - pytorch
    - pytest
    - pytest-cov
test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
