{% set name = "torch_scatter" %}
{% set version = "2.0.6" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c664656a6c006d5221b2d51ce51eca0bbf39e85a180fdd6d3ad42cb28b5a536

build:
  number: 1
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"    # [linux]
    - export CC="$GCC"   # [linux]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux]
  host:
    - python
    - pip
    - pytorch-gpu  # [linux]
    - pytorch-cpu  # [osx]
    - setuptools
    - pytest-runner
  run:
    - python
    - pytorch
    - {{ pin_compatible('pytorch-gpu') }}  # [linux]
    - {{ pin_compatible('pytorch-cpu') }}  # [osx]
    - pytest
    - pytest-cov
test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/pytorch_scatter

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
