{% set name = "torch_scatter" %}
{% set version = "2.0.4" %}

package:
  name: py{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db6c9eca919b86f3eb6102dd0e1215af72e39ed3a4e8d142e6a21d3f20d5c244
  patches:
    - remove_cuda_runtime_error.patch

build:
  number: 0
  skip: true  # [win]
  script:
    - export FORCE_CUDA="1"
    - export CC=${PREFIX}/bin/gcc
    - export NVCC_FLAGS="-DCUDA_HOST_COMPILER=${CC}"
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux and cuda_compiler_version != 'None']
  host:
    - python
    - pip
    - pytorch
    - setuptools
    - pytest-runner
  run:
    - python
    - pytorch
    - pytest
    - pytest-cov
test:
  imports:
    - torch_scatter
about:
  home: https://github.com/rusty1s/torch-scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/rusty1s/torch-scatter

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
